# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_bookings_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_from_booking_db(object):
    def setupUi(self, delete_from_booking_db):
        delete_from_booking_db.setObjectName("delete_from_booking_db")
        delete_from_booking_db.resize(378, 114)
        self.centralwidget = QtWidgets.QWidget(delete_from_booking_db)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_from_animal_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_from_animal_db_button.setGeometry(QtCore.QRect(10, 40, 361, 31))
        self.delete_from_animal_db_button.setObjectName("delete_from_animal_db_button")
        self.row_id_entry_for_delete = QtWidgets.QLineEdit(self.centralwidget)
        self.row_id_entry_for_delete.setGeometry(QtCore.QRect(60, 10, 311, 21))
        self.row_id_entry_for_delete.setObjectName("row_id_entry_for_delete")
        self.row_id_label = QtWidgets.QLabel(self.centralwidget)
        self.row_id_label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.row_id_label.setObjectName("row_id_label")
        delete_from_booking_db.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_from_booking_db)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 21))
        self.menubar.setObjectName("menubar")
        delete_from_booking_db.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_from_booking_db)
        self.statusbar.setObjectName("statusbar")
        delete_from_booking_db.setStatusBar(self.statusbar)

        self.retranslateUi(delete_from_booking_db)
        QtCore.QMetaObject.connectSlotsByName(delete_from_booking_db)

    def retranslateUi(self, delete_from_booking_db):
        _translate = QtCore.QCoreApplication.translate
        delete_from_booking_db.setWindowTitle(_translate("delete_from_booking_db", "DELETE from Bookings"))
        self.delete_from_animal_db_button.setText(_translate("delete_from_booking_db", "Delelte From Database"))
        self.row_id_label.setText(_translate("delete_from_booking_db", "Row ID"))
