# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_fs_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_fs_info(object):
    def setupUi(self, delete_fs_info):
        delete_fs_info.setObjectName("delete_fs_info")
        delete_fs_info.resize(376, 114)
        self.centralwidget = QtWidgets.QWidget(delete_fs_info)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_from_animal_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_from_animal_db_button.setGeometry(QtCore.QRect(10, 40, 361, 31))
        self.delete_from_animal_db_button.setObjectName("delete_from_animal_db_button")
        self.row_id_entry_for_delete = QtWidgets.QLineEdit(self.centralwidget)
        self.row_id_entry_for_delete.setGeometry(QtCore.QRect(60, 10, 311, 21))
        self.row_id_entry_for_delete.setObjectName("row_id_entry_for_delete")
        self.row_id_label = QtWidgets.QLabel(self.centralwidget)
        self.row_id_label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.row_id_label.setObjectName("row_id_label")
        delete_fs_info.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_fs_info)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 376, 21))
        self.menubar.setObjectName("menubar")
        delete_fs_info.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_fs_info)
        self.statusbar.setObjectName("statusbar")
        delete_fs_info.setStatusBar(self.statusbar)

        self.retranslateUi(delete_fs_info)
        QtCore.QMetaObject.connectSlotsByName(delete_fs_info)

    def retranslateUi(self, delete_fs_info):
        _translate = QtCore.QCoreApplication.translate
        delete_fs_info.setWindowTitle(_translate("delete_fs_info", "DELETE from Food and Storage"))
        self.delete_from_animal_db_button.setText(_translate("delete_fs_info", "Delelte From Database"))
        self.row_id_label.setText(_translate("delete_fs_info", "Row ID"))
