# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_food_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_food_window(object):
    def setupUi(self, edit_food_window):
        edit_food_window.setObjectName("edit_food_window")
        edit_food_window.resize(408, 202)
        self.centralwidget = QtWidgets.QWidget(edit_food_window)
        self.centralwidget.setObjectName("centralwidget")
        self.supplier_email_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_email_label.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.supplier_email_label.setObjectName("supplier_email_label")
        self.supplier_phone_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_phone_label.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.supplier_phone_label.setObjectName("supplier_phone_label")
        self.supplier_phone_label_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_phone_label_entry.setGeometry(QtCore.QRect(130, 70, 271, 20))
        self.supplier_phone_label_entry.setObjectName("supplier_phone_label_entry")
        self.supplier_name_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_name_label.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.supplier_name_label.setObjectName("supplier_name_label")
        self.supplier_email_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_email_entry.setGeometry(QtCore.QRect(130, 100, 271, 20))
        self.supplier_email_entry.setObjectName("supplier_email_entry")
        self.supplier_name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_name_entry.setGeometry(QtCore.QRect(130, 40, 271, 20))
        self.supplier_name_entry.setObjectName("supplier_name_entry")
        self.add_food_to_d_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_food_to_d_button.setGeometry(QtCore.QRect(10, 130, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_food_to_d_button.setFont(font)
        self.add_food_to_d_button.setObjectName("add_food_to_d_button")
        self.rowid_label = QtWidgets.QLabel(self.centralwidget)
        self.rowid_label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.rowid_label.setObjectName("rowid_label")
        self.supplier_name_entry_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_name_entry_2.setGeometry(QtCore.QRect(130, 10, 271, 21))
        self.supplier_name_entry_2.setObjectName("supplier_name_entry_2")
        edit_food_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(edit_food_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 21))
        self.menubar.setObjectName("menubar")
        edit_food_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edit_food_window)
        self.statusbar.setObjectName("statusbar")
        edit_food_window.setStatusBar(self.statusbar)

        self.retranslateUi(edit_food_window)
        QtCore.QMetaObject.connectSlotsByName(edit_food_window)

    def retranslateUi(self, edit_food_window):
        _translate = QtCore.QCoreApplication.translate
        edit_food_window.setWindowTitle(_translate("edit_food_window", "Edit Food Entry"))
        self.supplier_email_label.setText(_translate("edit_food_window", "Supplier Email Adress"))
        self.supplier_phone_label.setText(_translate("edit_food_window", "Supplier Phone Number"))
        self.supplier_name_label.setText(_translate("edit_food_window", "Supplier Name"))
        self.add_food_to_d_button.setText(_translate("edit_food_window", "Update Database"))
        self.rowid_label.setText(_translate("edit_food_window", "Row ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_food_window = QtWidgets.QMainWindow()
    ui = Ui_edit_food_window()
    ui.setupUi(edit_food_window)
    edit_food_window.show()
    sys.exit(app.exec_())
