# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_animal_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_animal_window(object):
    def setupUi(self, edit_animal_window):
        edit_animal_window.setObjectName("edit_animal_window")
        edit_animal_window.resize(515, 595)
        self.centralwidget = QtWidgets.QWidget(edit_animal_window)
        self.centralwidget.setObjectName("centralwidget")
        self.file_name_display_label = QtWidgets.QLabel(self.centralwidget)
        self.file_name_display_label.setGeometry(QtCore.QRect(100, 220, 401, 16))
        self.file_name_display_label.setObjectName("file_name_display_label")
        self.dob_entry = QtWidgets.QDateEdit(self.centralwidget)
        self.dob_entry.setGeometry(QtCore.QRect(100, 340, 401, 22))
        self.dob_entry.setObjectName("dob_entry")
        self.animal_medical_notes_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_medical_notes_label.setGeometry(QtCore.QRect(20, 370, 141, 21))
        self.animal_medical_notes_label.setObjectName("animal_medical_notes_label")
        self.animal_breed_cb = QtWidgets.QComboBox(self.centralwidget)
        self.animal_breed_cb.setGeometry(QtCore.QRect(100, 310, 401, 22))
        self.animal_breed_cb.setObjectName("animal_breed_cb")
        self.animal_name_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_name_label.setGeometry(QtCore.QRect(20, 250, 141, 21))
        self.animal_name_label.setObjectName("animal_name_label")
        self.update_animal_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_animal_db_button.setGeometry(QtCore.QRect(20, 510, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.update_animal_db_button.setFont(font)
        self.update_animal_db_button.setObjectName("update_animal_db_button")
        self.animal_species_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_species_label.setGeometry(QtCore.QRect(20, 280, 141, 21))
        self.animal_species_label.setObjectName("animal_species_label")
        self.animal_name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.animal_name_entry.setGeometry(QtCore.QRect(100, 250, 401, 20))
        self.animal_name_entry.setObjectName("animal_name_entry")
        self.animal_file_name_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_file_name_label.setGeometry(QtCore.QRect(20, 220, 51, 16))
        self.animal_file_name_label.setObjectName("animal_file_name_label")
        self.medical_notes_entry = QtWidgets.QTextEdit(self.centralwidget)
        self.medical_notes_entry.setGeometry(QtCore.QRect(100, 370, 401, 131))
        self.medical_notes_entry.setObjectName("medical_notes_entry")
        self.animal_dob_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_dob_label.setGeometry(QtCore.QRect(20, 340, 141, 21))
        self.animal_dob_label.setObjectName("animal_dob_label")
        self.animal_species_cb = QtWidgets.QComboBox(self.centralwidget)
        self.animal_species_cb.setGeometry(QtCore.QRect(100, 280, 401, 22))
        self.animal_species_cb.setObjectName("animal_species_cb")
        self.animal_breed_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_breed_label.setGeometry(QtCore.QRect(20, 310, 141, 21))
        self.animal_breed_label.setObjectName("animal_breed_label")
        self.animal_photo_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_photo_label.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.animal_photo_label.setObjectName("animal_photo_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 401, 171))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.supplier_name_entry_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_name_entry_2.setGeometry(QtCore.QRect(100, 0, 401, 21))
        self.supplier_name_entry_2.setObjectName("supplier_name_entry_2")
        self.rowid_label = QtWidgets.QLabel(self.centralwidget)
        self.rowid_label.setGeometry(QtCore.QRect(20, 0, 81, 21))
        self.rowid_label.setObjectName("rowid_label")
        edit_animal_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(edit_animal_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        edit_animal_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edit_animal_window)
        self.statusbar.setObjectName("statusbar")
        edit_animal_window.setStatusBar(self.statusbar)

        self.retranslateUi(edit_animal_window)
        QtCore.QMetaObject.connectSlotsByName(edit_animal_window)

    def retranslateUi(self, edit_animal_window):
        _translate = QtCore.QCoreApplication.translate
        edit_animal_window.setWindowTitle(_translate("edit_animal_window", "Edit Entry"))
        self.file_name_display_label.setText(_translate("edit_animal_window", "-No File Selected-"))
        self.animal_medical_notes_label.setText(_translate("edit_animal_window", "Medical Notes"))
        self.animal_name_label.setText(_translate("edit_animal_window", "Name"))
        self.update_animal_db_button.setText(_translate("edit_animal_window", "Update Database"))
        self.animal_species_label.setText(_translate("edit_animal_window", "Species"))
        self.animal_file_name_label.setText(_translate("edit_animal_window", "File Name"))
        self.animal_dob_label.setText(_translate("edit_animal_window", "Date of Birth"))
        self.animal_breed_label.setText(_translate("edit_animal_window", "Breed"))
        self.animal_photo_label.setText(_translate("edit_animal_window", "Photo"))
        self.rowid_label.setText(_translate("edit_animal_window", "Row ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_animal_window = QtWidgets.QMainWindow()
    ui = Ui_edit_animal_window()
    ui.setupUi(edit_animal_window)
    edit_animal_window.show()
    sys.exit(app.exec_())
