# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_food_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_food_entry_window(object):
    def setupUi(self, food_entry_window):
        food_entry_window.setObjectName("food_entry_window")
        food_entry_window.resize(439, 172)
        self.centralwidget = QtWidgets.QWidget(food_entry_window)
        self.centralwidget.setObjectName("centralwidget")
        self.supplier_name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_name_entry.setGeometry(QtCore.QRect(140, 10, 271, 20))
        self.supplier_name_entry.setObjectName("supplier_name_entry")
        self.supplier_email_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_email_label.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.supplier_email_label.setObjectName("supplier_email_label")
        self.supplier_email_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_email_entry.setGeometry(QtCore.QRect(140, 70, 271, 20))
        self.supplier_email_entry.setObjectName("supplier_email_entry")
        self.supplier_phone_label_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_phone_label_entry.setGeometry(QtCore.QRect(140, 40, 271, 20))
        self.supplier_phone_label_entry.setObjectName("supplier_phone_label_entry")
        self.supplier_phone_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_phone_label.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.supplier_phone_label.setObjectName("supplier_phone_label")
        self.supplier_name_label = QtWidgets.QLabel(self.centralwidget)
        self.supplier_name_label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.supplier_name_label.setObjectName("supplier_name_label")
        self.add_food_to_d_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_food_to_d_button.setGeometry(QtCore.QRect(20, 100, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_food_to_d_button.setFont(font)
        self.add_food_to_d_button.setObjectName("add_food_to_d_button")
        food_entry_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(food_entry_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 21))
        self.menubar.setObjectName("menubar")
        food_entry_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(food_entry_window)
        self.statusbar.setObjectName("statusbar")
        food_entry_window.setStatusBar(self.statusbar)

        self.retranslateUi(food_entry_window)
        QtCore.QMetaObject.connectSlotsByName(food_entry_window)

    def retranslateUi(self, food_entry_window):
        _translate = QtCore.QCoreApplication.translate
        food_entry_window.setWindowTitle(_translate("food_entry_window", "Add Food"))
        self.supplier_email_label.setText(_translate("food_entry_window", "Supplier Email Adress"))
        self.supplier_phone_label.setText(_translate("food_entry_window", "Supplier Phone Number"))
        self.supplier_name_label.setText(_translate("food_entry_window", "Supplier Name"))
        self.add_food_to_d_button.setText(_translate("food_entry_window", "Add to Database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    food_entry_window = QtWidgets.QMainWindow()
    ui = Ui_food_entry_window()
    ui.setupUi(food_entry_window)
    food_entry_window.show()
    sys.exit(app.exec_())
