# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_animal_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animal_entry_window(object):
    def setupUi(self, animal_entry_window):
        animal_entry_window.setObjectName("animal_entry_window")
        animal_entry_window.resize(532, 575)
        self.centralwidget = QtWidgets.QWidget(animal_entry_window)
        self.centralwidget.setObjectName("centralwidget")
        self.animal_name_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_name_label.setGeometry(QtCore.QRect(20, 230, 141, 21))
        self.animal_name_label.setObjectName("animal_name_label")
        self.animal_species_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_species_label.setGeometry(QtCore.QRect(20, 260, 141, 21))
        self.animal_species_label.setObjectName("animal_species_label")
        self.animal_breed_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_breed_label.setGeometry(QtCore.QRect(20, 290, 141, 21))
        self.animal_breed_label.setObjectName("animal_breed_label")
        self.animal_dob_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_dob_label.setGeometry(QtCore.QRect(20, 320, 141, 21))
        self.animal_dob_label.setObjectName("animal_dob_label")
        self.animal_medical_notes_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_medical_notes_label.setGeometry(QtCore.QRect(20, 350, 141, 21))
        self.animal_medical_notes_label.setObjectName("animal_medical_notes_label")
        self.animal_name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.animal_name_entry.setGeometry(QtCore.QRect(100, 230, 401, 20))
        self.animal_name_entry.setObjectName("animal_name_entry")
        self.dob_entry = QtWidgets.QDateEdit(self.centralwidget)
        self.dob_entry.setGeometry(QtCore.QRect(100, 320, 401, 22))
        self.dob_entry.setObjectName("dob_entry")
        self.animal_species_cb = QtWidgets.QComboBox(self.centralwidget)
        self.animal_species_cb.setGeometry(QtCore.QRect(100, 260, 401, 22))
        self.animal_species_cb.setObjectName("animal_species_cb")
        self.animal_breed_cb = QtWidgets.QComboBox(self.centralwidget)
        self.animal_breed_cb.setGeometry(QtCore.QRect(100, 290, 401, 22))
        self.animal_breed_cb.setObjectName("animal_breed_cb")
        self.medical_notes_entry = QtWidgets.QTextEdit(self.centralwidget)
        self.medical_notes_entry.setGeometry(QtCore.QRect(100, 350, 401, 131))
        self.medical_notes_entry.setObjectName("medical_notes_entry")
        self.animal_photo_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_photo_label.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.animal_photo_label.setObjectName("animal_photo_label")
        self.animal_file_name_label = QtWidgets.QLabel(self.centralwidget)
        self.animal_file_name_label.setGeometry(QtCore.QRect(20, 200, 51, 16))
        self.animal_file_name_label.setObjectName("animal_file_name_label")
        self.file_name_display_label = QtWidgets.QLabel(self.centralwidget)
        self.file_name_display_label.setGeometry(QtCore.QRect(100, 200, 401, 16))
        self.file_name_display_label.setObjectName("file_name_display_label")
        self.add_animal_to_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_animal_to_db_button.setGeometry(QtCore.QRect(20, 490, 481, 41))
        self.add_animal_to_db_button.setObjectName("add_animal_to_db_button")
        self.animal_photo_show = QtWidgets.QLabel(self.centralwidget)
        self.animal_photo_show.setGeometry(QtCore.QRect(100, 10, 401, 181))
        self.animal_photo_show.setText("")
        self.animal_photo_show.setAlignment(QtCore.Qt.AlignCenter)
        self.animal_photo_show.setObjectName("animal_photo_show")
        animal_entry_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(animal_entry_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        animal_entry_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(animal_entry_window)
        self.statusbar.setObjectName("statusbar")
        animal_entry_window.setStatusBar(self.statusbar)

        self.retranslateUi(animal_entry_window)
        QtCore.QMetaObject.connectSlotsByName(animal_entry_window)

    def retranslateUi(self, animal_entry_window):
        _translate = QtCore.QCoreApplication.translate
        animal_entry_window.setWindowTitle(_translate("animal_entry_window", "Enter Animal Information"))
        self.animal_name_label.setText(_translate("animal_entry_window", "Name"))
        self.animal_species_label.setText(_translate("animal_entry_window", "Species"))
        self.animal_breed_label.setText(_translate("animal_entry_window", "Breed"))
        self.animal_dob_label.setText(_translate("animal_entry_window", "Date of Birth"))
        self.animal_medical_notes_label.setText(_translate("animal_entry_window", "Medical Notes"))
        self.animal_photo_label.setText(_translate("animal_entry_window", "Photo"))
        self.animal_file_name_label.setText(_translate("animal_entry_window", "File Name"))
        self.file_name_display_label.setText(_translate("animal_entry_window", "-No File Selected-"))
        self.add_animal_to_db_button.setText(_translate("animal_entry_window", "Add Animal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    animal_entry_window = QtWidgets.QMainWindow()
    ui = Ui_animal_entry_window()
    ui.setupUi(animal_entry_window)
    animal_entry_window.show()
    sys.exit(app.exec_())
