# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_booking_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_booking_entry_window(object):
    def setupUi(self, booking_entry_window):
        booking_entry_window.setObjectName("booking_entry_window")
        booking_entry_window.resize(399, 363)
        self.centralwidget = QtWidgets.QWidget(booking_entry_window)
        self.centralwidget.setObjectName("centralwidget")
        self.customer_name_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_name_label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.customer_name_label.setObjectName("customer_name_label")
        self.customer_phone_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_phone_label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.customer_phone_label.setObjectName("customer_phone_label")
        self.customer_email_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_email_label.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.customer_email_label.setObjectName("customer_email_label")
        self.customer_address_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_address_label.setGeometry(QtCore.QRect(20, 100, 81, 21))
        self.customer_address_label.setObjectName("customer_address_label")
        self.private_horse_label = QtWidgets.QLabel(self.centralwidget)
        self.private_horse_label.setGeometry(QtCore.QRect(20, 180, 81, 21))
        self.private_horse_label.setObjectName("private_horse_label")
        self.event_type_label = QtWidgets.QLabel(self.centralwidget)
        self.event_type_label.setGeometry(QtCore.QRect(20, 150, 81, 21))
        self.event_type_label.setObjectName("event_type_label")
        self.horse_name_label = QtWidgets.QLabel(self.centralwidget)
        self.horse_name_label.setGeometry(QtCore.QRect(20, 210, 81, 21))
        self.horse_name_label.setObjectName("horse_name_label")
        self.date_of_event_label = QtWidgets.QLabel(self.centralwidget)
        self.date_of_event_label.setGeometry(QtCore.QRect(20, 250, 81, 21))
        self.date_of_event_label.setObjectName("date_of_event_label")
        self.private_horse_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.private_horse_check_box.setGeometry(QtCore.QRect(110, 180, 271, 21))
        self.private_horse_check_box.setObjectName("private_horse_check_box")
        self.event_type_cb = QtWidgets.QComboBox(self.centralwidget)
        self.event_type_cb.setGeometry(QtCore.QRect(110, 150, 271, 22))
        self.event_type_cb.setObjectName("event_type_cb")
        self.horse_name_cb = QtWidgets.QComboBox(self.centralwidget)
        self.horse_name_cb.setGeometry(QtCore.QRect(110, 210, 271, 22))
        self.horse_name_cb.setObjectName("horse_name_cb")
        self.date_of_event_entry = QtWidgets.QDateEdit(self.centralwidget)
        self.date_of_event_entry.setGeometry(QtCore.QRect(110, 250, 271, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_of_event_entry.setFont(font)
        self.date_of_event_entry.setObjectName("date_of_event_entry")
        self.customer_name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.customer_name_entry.setGeometry(QtCore.QRect(110, 10, 271, 20))
        self.customer_name_entry.setObjectName("customer_name_entry")
        self.customer_phone_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.customer_phone_entry.setGeometry(QtCore.QRect(110, 40, 271, 20))
        self.customer_phone_entry.setObjectName("customer_phone_entry")
        self.customer_email_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.customer_email_entry.setGeometry(QtCore.QRect(110, 70, 271, 20))
        self.customer_email_entry.setObjectName("customer_email_entry")
        self.customer_adress_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.customer_adress_entry.setGeometry(QtCore.QRect(110, 100, 271, 20))
        self.customer_adress_entry.setObjectName("customer_adress_entry")
        self.add_booking_to_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_booking_to_db_button.setGeometry(QtCore.QRect(20, 290, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_booking_to_db_button.setFont(font)
        self.add_booking_to_db_button.setObjectName("add_booking_to_db_button")
        booking_entry_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(booking_entry_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 399, 21))
        self.menubar.setObjectName("menubar")
        booking_entry_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(booking_entry_window)
        self.statusbar.setObjectName("statusbar")
        booking_entry_window.setStatusBar(self.statusbar)

        self.retranslateUi(booking_entry_window)
        QtCore.QMetaObject.connectSlotsByName(booking_entry_window)

    def retranslateUi(self, booking_entry_window):
        _translate = QtCore.QCoreApplication.translate
        booking_entry_window.setWindowTitle(_translate("booking_entry_window", "Add Booking"))
        self.customer_name_label.setText(_translate("booking_entry_window", "Customer Name"))
        self.customer_phone_label.setText(_translate("booking_entry_window", "Phone Number"))
        self.customer_email_label.setText(_translate("booking_entry_window", "Email Adress"))
        self.customer_address_label.setText(_translate("booking_entry_window", "House Adress"))
        self.private_horse_label.setText(_translate("booking_entry_window", "Private Horse"))
        self.event_type_label.setText(_translate("booking_entry_window", "Type of Event"))
        self.horse_name_label.setText(_translate("booking_entry_window", "Horse Name"))
        self.date_of_event_label.setText(_translate("booking_entry_window", "Date"))
        self.private_horse_check_box.setText(_translate("booking_entry_window", "Check for \"yes\""))
        self.add_booking_to_db_button.setText(_translate("booking_entry_window", "Add Booking"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    booking_entry_window = QtWidgets.QMainWindow()
    ui = Ui_booking_entry_window()
    ui.setupUi(booking_entry_window)
    booking_entry_window.show()
    sys.exit(app.exec_())
