# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from animals_screen  import Ui_animals_screen
from fs_screen       import Ui_fs_screen
from bookings_screen import Ui_bookings_screen



class Ui_home_screen(object):

    def setupUi(self, home_screen):
        home_screen.setObjectName("home_screen")
        home_screen.resize(598, 355)
        self.centralwidget = QtWidgets.QWidget(home_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.animal_screen_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: open_animal_screen())
        self.animal_screen_button.setGeometry(QtCore.QRect(90, 80, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.animal_screen_button.setFont(font)
        self.animal_screen_button.setObjectName("animal_screen_button")

        self.cb_screen_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: open_cb_screen())
        self.cb_screen_button.setGeometry(QtCore.QRect(330, 80, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_screen_button.setFont(font)
        self.cb_screen_button.setObjectName("cb_screen_button")

        self.ev_screen_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: open_ev_screen())
        self.ev_screen_button.setGeometry(QtCore.QRect(330, 200, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ev_screen_button.setFont(font)
        self.ev_screen_button.setObjectName("ev_screen_button")

        self.fs_screen_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: open_fs_screen())
        self.fs_screen_button.setGeometry(QtCore.QRect(90, 200, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fs_screen_button.setFont(font)
        self.fs_screen_button.setObjectName("fs_screen_button")

        self.toggle_lang_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: toggle_lang())
        self.toggle_lang_button.setGeometry(QtCore.QRect(444, 2, 151, 31))
        self.toggle_lang_button.setObjectName("toggle_lang_button")
        home_screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home_screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        home_screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home_screen)
        self.statusbar.setObjectName("statusbar")
        home_screen.setStatusBar(self.statusbar)

        self.retranslateUi(home_screen)
        QtCore.QMetaObject.connectSlotsByName(home_screen)


        def open_animal_screen():
            self.window = QtWidgets
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_animals_screen()
            self.ui.setupUi(self.window)
            self.window.show()

            home_screen.hide()

        def open_cb_screen():
            self.window = QtWidgets
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_bookings_screen()
            self.ui.setupUi(self.window)
            self.window.show()

        def open_ev_screen():
            pass

        def open_fs_screen():
            self.window = QtWidgets
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_fs_screen()
            self.ui.setupUi(self.window)
            self.window.show()

        def toggle_lang():
            pass

    def retranslateUi(self, home_screen):
        _translate = QtCore.QCoreApplication.translate
        home_screen.setWindowTitle(_translate("home_screen", "Home Screen"))
        self.animal_screen_button.setText(_translate("home_screen", "Animals"))
        self.cb_screen_button.setText(_translate("home_screen", "Customers and Bookings"))
        self.ev_screen_button.setText(_translate("home_screen", "Equipment and Vehicles"))
        self.fs_screen_button.setText(_translate("home_screen", "Food and Storage"))
        self.toggle_lang_button.setText(_translate("home_screen", "Toggle English/German"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_screen = QtWidgets.QMainWindow()
    ui = Ui_home_screen()
    ui.setupUi(home_screen)
    home_screen.show()
    sys.exit(app.exec_())
