# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from login_error_message import Ui_login_error_message
from home_screen import Ui_home_screen

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_screen(object):


    def setupUi(self, login_screen):
        login_screen.setObjectName("login_screen")
        login_screen.resize(493, 303)
        self.centralwidget = QtWidgets.QWidget(login_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.username_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.username_entry.setGeometry(QtCore.QRect(180, 80, 251, 31))
        self.username_entry.setObjectName("username_entry")
        self.password_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.password_entry.setGeometry(QtCore.QRect(180, 120, 251, 31))
        self.password_entry.setObjectName("password_entry")
        self.usernamelabel = QtWidgets.QLabel(self.centralwidget)
        self.usernamelabel.setGeometry(QtCore.QRect(60, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordlabel.setGeometry(QtCore.QRect(60, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setObjectName("passwordlabel")

        self.login_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: verify_login())
        self.login_button.setGeometry(QtCore.QRect(180, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        login_screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 21))
        self.menubar.setObjectName("menubar")
        login_screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_screen)
        self.statusbar.setObjectName("statusbar")
        login_screen.setStatusBar(self.statusbar)

        self.retranslateUi(login_screen)
        QtCore.QMetaObject.connectSlotsByName(login_screen)

        def allow_login():
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_home_screen()
            self.ui.setupUi(self.window)
            self.window.show()
            login_screen.hide()

        def login_error():
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_login_error_message()
            self.ui.setupUi(self.window)
            self.window.show()

        def verify_login():
            if self.username_entry.text() == "vipin" and self.password_entry.text() == "123123":
                allow_login()
            else:
                login_error()

    def retranslateUi(self, login_screen):
        _translate = QtCore.QCoreApplication.translate
        login_screen.setWindowTitle(_translate("login_screen", "Login"))
        self.usernamelabel.setText(_translate("login_screen", "Username"))
        self.passwordlabel.setText(_translate("login_screen", "Password"))
        self.login_button.setText(_translate("login_screen", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_screen = QtWidgets.QMainWindow()
    ui = Ui_login_screen()
    ui.setupUi(login_screen)
    login_screen.show()
    sys.exit(app.exec_())
