# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_error_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_error_message(object):
    def setupUi(self, login_error_message):
        login_error_message.setObjectName("login_error_message")
        login_error_message.resize(417, 143)
        self.le_1 = QtWidgets.QLabel(login_error_message)
        self.le_1.setGeometry(QtCore.QRect(20, 20, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_1.setFont(font)
        self.le_1.setObjectName("le_1")
        self.le_2 = QtWidgets.QLabel(login_error_message)
        self.le_2.setGeometry(QtCore.QRect(120, 50, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_2.setFont(font)
        self.le_2.setObjectName("le_2")
        self.le_3 = QtWidgets.QLabel(login_error_message)
        self.le_3.setGeometry(QtCore.QRect(130, 100, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_3.setFont(font)
        self.le_3.setObjectName("le_3")

        self.retranslateUi(login_error_message)
        QtCore.QMetaObject.connectSlotsByName(login_error_message)

    def retranslateUi(self, login_error_message):
        _translate = QtCore.QCoreApplication.translate
        login_error_message.setWindowTitle(_translate("login_error_message", "LOGIN ERROR"))
        self.le_1.setText(_translate("login_error_message", "Either the username or password you have"))
        self.le_2.setText(_translate("login_error_message", "entered is incorrect."))
        self.le_3.setText(_translate("login_error_message", "Please try again"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_error_message = QtWidgets.QDialog()
    ui = Ui_login_error_message()
    ui.setupUi(login_error_message)
    login_error_message.show()
    sys.exit(app.exec_())
